# Generated by Django 4.0.1 on 2022-01-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_room', models.BooleanField(default=False)),
                ('is_checkpoint', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('is_guest', models.BooleanField(default=True)),
                ('img', models.ImageField(blank=True, upload_to='profiles/')),
                ('available_locks', models.ManyToManyField(to='main.Lock')),
            ],
        ),
    ]
