# Generated by Django 4.0.1 on 2022-01-26 21:01

from django.db import migrations
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=main.utils.CustomImageField(blank=True, upload_to='profiles/'),
        ),
    ]
